repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: local
    hooks:
    -   id: ruff-check
        name: Lint python code with ruff
        language: system
        entry: pixi run ruff
        args: [check]
        files: \.py$
    -   id: ruff-format
        name: Format python code with ruff
        language: system
        entry: pixi run ruff
        args: [format]
        files: \.py$
