name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

  test-matrix:
    needs: pre-commit
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            pixi-platform: linux-64
          - os: macos-latest
            pixi-platform: osx-arm64
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.9.3
      with:
        pixi-version: v0.62.2
        cache: true
        environments: default pydantic-1-cpu

    - name: Run tests with pydantic >=2
      run: |
        pixi run test

    - name: Run tests with pydantic <2
      run: |
<<<<<<< HEAD
        pixi run --environment pydantic-1-cpu test
=======
        # TODO: Remove this once pydantic 1.0 support is dropped
        #       We remove absolv as femto needs pydantic >=2
        mamba remove  --name smee --yes "absolv" "absolv-base" "femto" "pint" "ambertools" --force
        mamba install --name smee --yes "pydantic <2"
        conda list
>>>>>>> 5966e47 (update)

    - name: Test examples with pydantic >=2
      run: |
        pixi run test-examples

    - name: Build docs
      run: |
        pixi run docs

    - name: CodeCov
      uses: codecov/codecov-action@v4.1.1
      with:
        file: ./coverage.xml
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}

  test:
    needs: test-matrix
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Check test matrix result
      run: |
        if [[ "${{ needs.test-matrix.result }}" != "success" ]]; then
          echo "One or more test matrix jobs failed or were cancelled."
          exit 1
        fi
