name: Publish Documentation

on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  deploy-docs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.9.3
      with:
        pixi-version: v0.62.2
        cache: true

    - name: Determine Version
      shell: bash
      run: |
        if [ "$GITHUB_REF" = "refs/heads/main" ]; then
          echo "VERSION=latest" >> $GITHUB_ENV
        elif [ "${GITHUB_REF#refs/tags/}" != "$GITHUB_REF" ]; then
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          echo "VERSION=$VERSION stable" >> $GITHUB_ENV
        else
          echo "Invalid ref: $GITHUB_REF"
          exit 1
        fi

    - name: Build and Deploy Documentation
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git config --global --add safe.directory "$PWD"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

        git fetch --all --prune
        git pull origin gh-pages --allow-unrelated-histories

        pixi run mike deploy --push --update-aliases $VERSION
